[tool.pytest.ini_options]
# Configure pytest options here
# https://docs.pytest.org/en/7.1.x/reference/reference.html#configuration-options

# Base URL for Playwright tests (matches the TS config)
base_url = "http://127.0.0.1:3000"

# You can add other pytest options here later if needed, e.g.:
# addopts = "-v --headed"
# testpaths = [
#     "demos",
#     "exercises",
#     "solutions"
# ]