# Gitpod configuration for the Playwright Deep Dive Workshop

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install & Run App
    init: |
      echo "Installing dependencies..."
      npm install
      npx playwright install --with-deps
    command: |
      echo "Starting Next.js app..."
      npm run dev

  - name: Test Terminal
    init: |
      echo "Waiting for the application to start on port 3000..."
      gp sync-await 3000
    command: |
      echo "-----------------------------------------------------"
      echo "Welcome to the Playwright Deep Dive Workshop!"
      echo "Your app is running and ready."
      echo "Use this terminal to run your tests."
      echo "e.g., npx playwright test (Node version: $(node -v))"
      echo "-----------------------------------------------------"
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-browser
    name: Application
    description: The Next.js test application.

  - port: 9323
    onOpen: ignore
    name: Playwright Report
    description: Port for 'npx playwright show-report'

vscode:
  extensions:
    - ms-playwright.playwright
    - ms-python.python
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
