# Gitpod configuration for the Playwright Deep Dive Workshop

tasks:
  - name: Install Node.js & Dependencies
    before: |
      # Install Node.js 18 using official NodeSource setup
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Verify installation
      echo "Node version: $(node -v)"
      echo "npm version: $(npm -v)"
    init: |
      echo "Installing dependencies..."
      npm install
      npx playwright install --with-deps
    command: |
      echo "Starting Next.js app..."
      npm run dev

  - name: Test Terminal
    before: |
      # Ensure Node.js is available in this terminal too
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
    init: |
      echo "Waiting for the application to start on port 3000..."
      gp sync-await 3000
    command: |
      echo "-----------------------------------------------------"
      echo "Welcome to the Playwright Deep Dive Workshop!"
      echo "Your app is running and ready."
      echo "Node version: $(node -v)"
      echo "npm version: $(npm -v)"
      echo "Use this terminal to run your tests."
      echo "e.g., npx playwright test"
      echo "-----------------------------------------------------"
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-browser
    name: Application
    description: The Next.js test application.

  - port: 9323
    onOpen: ignore
    name: Playwright Report
    description: Port for 'npx playwright show-report'

vscode:
  extensions:
    - ms-playwright.playwright
    - ms-python.python
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
