# Gitpod configuration for the Playwright Deep Dive Workshop
# This file automates the setup for attendees (Plan A).

tasks:
  - name: Install & Run App
    before: |
      # Configure nvm for all shells in this task
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install 18
      nvm use 18
      nvm alias default 18
    init: |
      echo "Installing dependencies..."
      npm install
      npx playwright install --with-deps
    command: |
      echo "Starting Next.js app..."
      npm run dev

  - name: Test Terminal
    before: |
      # Configure nvm for this terminal
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm use default
    init: |
      echo "Waiting for the application to start on port 3000..."
      gp sync-await 3000
    command: |
      echo "-----------------------------------------------------"
      echo "Welcome to the Playwright Deep Dive Workshop!"
      echo "Your app is running and ready."
      echo "Use this terminal to run your tests."
      echo "e.g., npx playwright test (Node version: $(node -v))"
      echo "-----------------------------------------------------"
    openMode: split-right

ports:
  # Expose the Next.js app
  - port: 3000
    onOpen: open-browser # Automatically opens the app in a new tab
    name: Application
    description: The Next.js test application.

  # Expose the Playwright report port
  - port: 9323
    onOpen: ignore
    name: Playwright Report
    description: Port for 'npx playwright show-report'

vscode:
  extensions:
    - ms-playwright.playwright # Official Playwright extension
    - ms-python.python # For the Python track
    - dbaeumer.vscode-eslint # Linting
    - esbenp.prettier-vscode # Code formatting
